<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('users', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('email')->unique(); $t->timestamp('email_verified_at')->nullable(); $t->string('password'); $t->boolean('is_admin')->default(false); $t->rememberToken(); $t->timestamps(); });
        Schema::create('password_reset_tokens', function (Blueprint $t) { $t->string('email')->primary(); $t->string('token'); $t->timestamp('created_at')->nullable(); });
        Schema::create('sessions', function (Blueprint $t) { $t->string('id')->primary(); $t->foreignId('user_id')->nullable()->index(); $t->string('ip_address',45)->nullable(); $t->text('user_agent')->nullable(); $t->longText('payload'); $t->integer('last_activity')->index(); });
        Schema::create('cache', function (Blueprint $t) { $t->string('key')->primary(); $t->mediumText('value'); $t->integer('expiration'); });
        Schema::create('cache_locks', function (Blueprint $t) { $t->string('key')->primary(); $t->string('owner'); $t->integer('expiration'); });
        Schema::create('jobs', function (Blueprint $t) { $t->id(); $t->string('queue')->index(); $t->longText('payload'); $t->unsignedTinyInteger('attempts'); $t->unsignedInteger('reserved_at')->nullable(); $t->unsignedInteger('available_at'); $t->unsignedInteger('created_at'); });
        Schema::create('job_batches', function (Blueprint $t) { $t->string('id')->primary(); $t->string('name'); $t->integer('total_jobs'); $t->integer('pending_jobs'); $t->integer('failed_jobs'); $t->longText('failed_job_ids'); $t->mediumText('options')->nullable(); $t->integer('cancelled_at')->nullable(); $t->integer('created_at'); $t->integer('finished_at')->nullable(); });
        Schema::create('failed_jobs', function (Blueprint $t) { $t->id(); $t->string('uuid')->unique(); $t->text('connection'); $t->text('queue'); $t->longText('payload'); $t->longText('exception'); $t->timestamp('failed_at')->useCurrent(); });
        Schema::create('categories', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->timestamps(); });
        Schema::create('collections', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->timestamps(); });
        Schema::create('products', function (Blueprint $t) { $t->id(); $t->foreignId('category_id')->constrained()->restrictOnDelete(); $t->foreignId('collection_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('slug')->unique(); $t->text('description'); $t->text('care')->nullable(); $t->string('material')->nullable(); $t->string('colour')->nullable(); $t->string('style')->nullable(); $t->string('occasion')->nullable(); $t->boolean('published')->default(false)->index(); $t->timestamps(); });
        Schema::create('product_variants', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('sku')->unique(); $t->string('size')->nullable(); $t->string('colour')->nullable(); $t->string('material')->nullable(); $t->string('set_size')->nullable(); $t->unsignedInteger('price_paise'); $t->unsignedInteger('stock')->default(0); $t->unsignedInteger('reserved')->default(0); $t->timestamps(); });
        Schema::create('product_images', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('path'); $t->string('alt'); $t->unsignedInteger('position')->default(0); $t->timestamps(); });
        Schema::create('addresses', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('phone',15); $t->string('line1'); $t->string('line2')->nullable(); $t->string('city'); $t->string('state'); $t->char('pincode',6); $t->boolean('is_default')->default(false); $t->timestamps(); });
        Schema::create('cart_items', function (Blueprint $t) { $t->id(); $t->string('cart_token',64)->index(); $t->foreignId('variant_id')->constrained('product_variants')->cascadeOnDelete(); $t->unsignedInteger('quantity'); $t->unique(['cart_token','variant_id']); $t->timestamps(); });
        Schema::create('wishlists', function (Blueprint $t) { $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->primary(['user_id','product_id']); });
        Schema::create('coupons', function (Blueprint $t) { $t->id(); $t->string('code')->unique(); $t->enum('type',['fixed','percent']); $t->unsignedInteger('value'); $t->unsignedInteger('min_order_paise')->default(0); $t->unsignedInteger('usage_limit')->nullable(); $t->unsignedInteger('used')->default(0); $t->timestamp('expires_at')->nullable(); $t->boolean('active')->default(true); $t->timestamps(); });
        Schema::create('settings', function (Blueprint $t) { $t->string('key')->primary(); $t->text('value')->nullable(); });
        Schema::create('orders', function (Blueprint $t) { $t->id(); $t->uuid('checkout_token')->unique(); $t->string('cart_token',64)->nullable(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('coupon_id')->nullable()->constrained()->nullOnDelete(); $t->string('email'); $t->json('shipping_address'); $t->enum('payment_method',['razorpay','cod'])->default('razorpay'); $t->enum('status',['pending_payment','paid','processing','shipped','delivered','cancelled','return_requested','returned','refunded'])->default('pending_payment'); $t->unsignedInteger('subtotal_paise'); $t->unsignedInteger('discount_paise')->default(0); $t->unsignedInteger('shipping_paise')->default(0); $t->unsignedInteger('tax_paise')->default(0); $t->unsignedInteger('total_paise'); $t->string('gateway_order_id')->nullable()->unique(); $t->string('tracking_number')->nullable(); $t->timestamp('reservation_expires_at')->nullable()->index(); $t->timestamps(); });
        Schema::create('order_items', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete(); $t->string('sku'); $t->string('name'); $t->string('options')->nullable(); $t->unsignedInteger('unit_price_paise'); $t->unsignedInteger('quantity'); });
        Schema::create('payment_attempts', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->string('gateway_order_id')->unique(); $t->string('gateway_payment_id')->nullable()->unique(); $t->string('status')->default('created'); $t->json('response')->nullable(); $t->timestamps(); });
        Schema::create('gateway_events', function (Blueprint $t) { $t->id(); $t->string('gateway_event_id')->unique(); $t->string('event_type'); $t->timestamps(); });
        Schema::create('order_events', function (Blueprint $t) { $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('from_status')->nullable(); $t->string('to_status'); $t->text('note')->nullable(); $t->timestamps(); });
        Schema::create('enquiries', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('email'); $t->text('message'); $t->timestamps(); });
    }
    public function down(): void { foreach (['enquiries','order_events','gateway_events','payment_attempts','order_items','orders','settings','coupons','wishlists','cart_items','addresses','product_images','product_variants','products','collections','categories','failed_jobs','job_batches','jobs','cache_locks','cache','sessions','password_reset_tokens','users'] as $table) Schema::dropIfExists($table); }
};
