@extends('layouts.app') @section('title','Shop earrings & bangles · '.$brand) @section('content')
<div class="mb-8 md:mb-10"><p class="text-[10px] uppercase tracking-[.2em] gold font-semibold">The collection</p><h1 class="section-title mt-3">Find your next favourite</h1><p class="muted mt-4 max-w-2xl">Explore earrings and bangles by material, colour, style and occasion.</p></div>
<form action="{{route('shop')}}" method="get" class="card p-4 md:p-5 mb-9 grid gap-3 md:grid-cols-4">
<input class="field" type="search" name="q" value="{{request('q')}}" placeholder="Search pieces" aria-label="Search products">
<select class="field" name="category" aria-label="Category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{$category->slug}}" @selected(request('category')===$category->slug)>{{$category->name}}</option>@endforeach</select>
@foreach(['material','colour','style','occasion'] as $field)<select class="field" name="{{$field}}" aria-label="{{ucfirst($field)}}"><option value="">All {{ $field }}s</option>@foreach($filters->pluck($field)->filter()->unique()->sort() as $value)<option value="{{$value}}" @selected(request($field)===$value)>{{$value}}</option>@endforeach</select>@endforeach
<input class="field" name="min" type="number" min="0" step="1" value="{{request('min')}}" placeholder="Min ₹" aria-label="Minimum price"><input class="field" name="max" type="number" min="0" step="1" value="{{request('max')}}" placeholder="Max ₹" aria-label="Maximum price">
<select class="field" name="sort" aria-label="Sort products"><option value="latest">Newest</option><option value="price_asc" @selected(request('sort')==='price_asc')>Price: low to high</option><option value="price_desc" @selected(request('sort')==='price_desc')>Price: high to low</option></select>
<label class="flex gap-2 items-center text-sm px-1"><input type="checkbox" name="available" value="1" @checked(request('available'))> In stock</label><button class="button" type="submit">Apply filters</button>
</form>
@if($products->count())<div class="flex justify-between items-center mb-5 text-sm text-stone-500"><span>{{$products->total()}} pieces</span><span>Curated for you</span></div><div class="grid-products">@foreach($products as $item)@include('store._card')@endforeach</div><div class="py-10">{{$products->links()}}</div>@else<p class="card p-12 text-center">No pieces match those filters. <a class="underline" href="{{route('shop')}}">View all pieces</a></p>@endif @endsection